### ISSUE TITLE
really?!

### ISSUE THREAD

**Issue by farshidjahanmanesh** [1netanel/letterboxd-services#2]
hello dear.
i think you are copy this project from another one
this is the main : https://github.com/Hame-daani/letterboxd_util
why you don't fork it?!

**Comment by 1netanel** [comment]
not one line of your friend's code was used in my project, and why are you speaking for him ? he doesn't have a mouth ?
also he said he could  issue a DMCA and delete my repo.  so why doesn't he do that ?

**Comment by 1netanel** [comment]
he could have answerd me but instead he calls his friend, smh.
