### ISSUE TITLE
Use imdb id to search

### ISSUE THREAD

**Issue by VulumeCode** [1netanel/letterboxd-services#9]
For example, this movie https://letterboxd.com/film/q-1982/ has no results on Yify, Rarbg or Lime Torrents. But when you use the imdb id (tt0084556) it works. It can be fetched from the imdb link on the letterboxd page. It's indexed for almost all movies on these sites.

**Comment by 1netanel** [comment]
What browser are you using ?

**Comment by VulumeCode** [comment]
Firefox, but ah, I see in the code you already do this. I installed the plugin from mozilla.org. I hope it's legit, just outdated.

**Comment by 1netanel** [comment]
Yeah, the version in mozilla is just outdated.
